<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SignalR2.aspx.cs" Inherits="PedroMayo_WebASPNET.MAIN.SignalR2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-1.6.4.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../pedromayo/signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {
            //connection.start({ transport: ['webSockets', 'longPolling'] });

            // Declaro la proxy de la clase "ChatHub" to reference the hub. 
            var chat = $.connection.chatHub;

            // Método al lado del cliente que puede ser invocado desde el servidor
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };

            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.  
            $('#message').focus();

            // Start the connection.
            $.connection.hub.start().done(function () {
                //
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();                    
                });

                $('#getnames').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.getAllNames().done(function (stocks) {
                        $.each(stocks, function () {
                            alert(stocks[0]);
                        });
                    });
                });
            });
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="button" id="getnames" value="GetNames" />
        <input type="hidden" id="displayname" />
        <ul id="discussion">
        </ul>
    </div>
</asp:Content>
